export const REPLIT_API_BASE_URL = 'https://league-builder.replit.app';
export const FIREBASE_BASE_URL = "https://wlpn-roblox-default-rtdb.europe-west1.firebasedatabase.app";

export const API_ENDPOINTS = {
  STATS: `${REPLIT_API_BASE_URL}/api/stats`,
  TABLE: `${REPLIT_API_BASE_URL}/api/tables`,
  SCHEDULE: '/api/schedule',
  EXTERNAL_STATS: `${REPLIT_API_BASE_URL}/api/external/stats`,
  EXTERNAL_TABLE: `${REPLIT_API_BASE_URL}/api/external/table`,
  PLAYERS_HISTORY: `${REPLIT_API_BASE_URL}/players-history.json`,
  MATCHES: `${REPLIT_API_BASE_URL}/api/matches`,
};

export const POSITION_MAPPING: Record<string, string> = {
  'GK': 'Bramkarz',
  'DF': 'Obrońca',
  'CB': 'Obrońca',
  'LB': 'Obrońca',
  'RB': 'Obrońca',
  'LWB': 'Obrońca',
  'RWB': 'Obrońca',
  'DEF': 'Obrońca',
  'MF': 'Pomocnik',
  'CM': 'Pomocnik',
  'CDM': 'Pomocnik',
  'CAM': 'Pomocnik',
  'LM': 'Pomocnik',
  'RM': 'Pomocnik',
  'MID': 'Pomocnik',
  'FW': 'Napastnik',
  'ST': 'Napastnik',
  'RW': 'Napastnik',
  'LW': 'Napastnik',
  'ATT': 'Napastnik',
  'CF': 'Napastnik',
};

export const TEAM_ID_MAPPING: Record<string, string> = {
  '1': 'BOB', '2': 'CAN', '3': 'DRM', '4': 'DZ4', '5': 'BOS',
  '6': 'DZI', '7': 'MAK', '8': 'ZZB', '9': 'KSP', '10': 'PKS',
  '11': 'SET', '12': 'SPA', '13': 'USL', '14': 'ZKP'
};

export const COUNTRY_MAPPING: Record<string, string> = {
  'PL': 'Polska',
  'EN': 'Anglia',
  'DE': 'Niemcy',
  'FR': 'Francja',
  'ES': 'Hiszpania',
  'IT': 'Włochy',
  'BR': 'Brazylia',
  'AR': 'Argentyna',
  'PT': 'Portugalia',
  'NL': 'Holandia',
  'BE': 'Belgia',
  'HR': 'Chorwacja',
  'SE': 'Szwecja',
  'NO': 'Norwegia',
  'DK': 'Dania',
  'CH': 'Szwajcaria',
  'AT': 'Austria',
  'TR': 'Turcja',
  'UA': 'Ukraina',
  'CZ': 'Czechy',
  'SK': 'Słowacja',
  'HU': 'Węgry',
  'RO': 'Rumunia',
  'BG': 'Bułgaria',
  'GR': 'Grecja',
  'US': 'USA',
  'CA': 'Kanada',
  'MX': 'Meksyk',
  'UY': 'Urugwaj',
  'CL': 'Chile',
  'CO': 'Kolumbia',
  'MA': 'Maroko',
  'EG': 'Egipt',
  'SN': 'Senegal',
  'NG': 'Nigeria',
  'JP': 'Japonia',
  'KR': 'Korea Płd.',
  'AU': 'Australia',
  'RS': 'Serbia',
  'SI': 'Słowenia',
  'ME': 'Czarnogóra',
  'BA': 'Bośnia i Herc.',
  'AL': 'Albania',
  'IE': 'Irlandia',
  'FI': 'Finlandia',
  'IS': 'Islandia',
  'GE': 'Gruzja',
  'AM': 'Armenia',
};

